#!/bin/bash

# Commented lines cannot be ran on ARM

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install gcc
sudo apt-get install make
#sudo apt install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
sudo apt-get install gdb
sudo apt-get install python3
sudo apt-get install wireshark
sudo apt-get install net-tools
sudo apt-get install htop
sudo apt-get install nasm
sudo apt-get install ld
sudo apt-get install as
sudo apt-get install vim
sudo apt-get install neofetch

wget -O ~/.gdbinit-gef.py -q http://gef.blah.cat/py
echo source ~/.gdbinit-gef.py > ~/.gdbinit
#echo "set disassembly-flavor intel" >> ~/.gdbinit
echo "gef config context.show_registers_raw True" >> ~/.gdbinit

#bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
#x-www-browser https://www.jetbrains.com/toolbox-app/
