#!/bin/bash

# Change permissions to 777

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install gcc -y
sudo apt-get install python3
sudo apt-get install make -y
sudo apt install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu -y
sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
sudo apt-get install gdb -y
sudo apt-get install python3 -y
sudo apt-get install wireshark -y
sudo apt-get install john -y 
sudo apt-get install yersinia -y
sudo apt-get install net-tools -y
sudo apt-get install htop -y
sudo apt-get install nasm -y
sudo apt-get install ld -y
sudo apt-get install as -y
sudo apt-get install vim -y
sudo apt-get install bless -y
sudo apt-get install neofetch -y
sudo apt-get install tree -y
sudo apt-get install ascii -y
sudo apt-get install mlocate -y

wget -O ~/.gdbinit-gef.py -q http://gef.blah.cat/py
echo source ~/.gdbinit-gef.py > ~/.gdbinit
echo "set disassembly-flavor intel" >> ~/.gdbinit
echo "gef config context.show_registers_raw True" >> ~/.gdbinit

bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
x-www-browser https://www.jetbrains.com/toolbox-app/ &
